// svelte-app/src/PerfComp10.svelte
<!-- PerfComp10.svelte -->
<script>
    import PerfComp01 from "./PerfComp01.svelte";

    export let content = "1";
    const upper = content.toUpperCase();
</script>

<div>
    {#each Array(100) as _, i}
        <PerfComp01 {content} />
    {/each}
</div>

<div>
    {#each Array(100) as _, i}
        <PerfComp01 content={upper} />
    {/each}
</div>

// vue3-app/src/PerfComp10.vue
<script setup lang="ts">

  import PerfComp01 from "./PerfComp01.vue";
  const props = defineProps(['content']);
  const upper = props.content.toUpperCase();
</script>

<template>
  <div>
    <PerfComp01 v-for="i in Array(100)" :content />
  </div>

  <div>
    <PerfComp01 v-for="i in Array(100)" v-bind:content="upper" />
  </div>

</template>
